# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 我的学习笔记
subtitle: '宝剑锋从磨砺出，梅花香自苦寒来'
description: ''
keywords:
author: 感悟
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://git.wxzvip.com/blogs
root: /blogs/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''


# 覆盖主题配置
## 在站点的 _config.yml 配置文件中配置你的主题，就不需要 fork 一份主题并维护主题独立的配置文件
theme_config:
  # Create your custom files in site directory `source/_data` and uncomment needed files below.
  custom_file_path:
    style: source/_data/styles.styl

  favicon:
    small: /images/favicon.ico
    medium: /images/favicon.ico

  footer:
    since: 2019
    icon:
      # Icon name in Font Awesome. See: https://fontawesome.com/v4.7.0/icons/
      # `heart` is recommended with animation in red (#ff0000).
      name: heart #user
      # If you want to animate the icon, set it to true.
      animated: true #false
      # Change the color of icon, using Hex Code.
      color: "#ff0000" #"#808080"
    beian:
      enable: true
      icp: 鲁ICP备17027395号

  scheme: Gemini

  avatar:
    # Replace the default image and set the url here.
    url: http://image.wxzvip.cn/avatar.jpg #/images/avatar.gif
    # If true, the avatar will be dispalyed in circle.
    rounded: true

  social:
    GitHub: https://github.com/suresking || github
    E-Mail: mailto:w@wxzvip.cn || envelope

  links:
    必应: https://cn.bing.com

  custom_logo: http://image.wxzvip.cn/tyj-logo.png #/uploads/custom-logo.jpg

  codeblock:
    # Code Highlight theme
    # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
    # See: https://github.com/chriskempson/tomorrow-theme
    highlight_theme: galactic

